# Scraper ~ PHP + Node.JS

language: php

php: 7.0

git:
  depth: 8

install: composer install && composer npm-install

before_script: composer copy-env && composer mk-cache

script:
  - composer validate
  - composer test
  - composer build
  - composer version.json

after_script:
  - git status
  - cat index.json && cat version.json
  # Server environment.
  - php -r 'print_r([ $_SERVER, php_sapi_name() ]);'

# end.
